[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_VERSION = "1.0.0"
  REACT_APP_BUILD_TIME = "$DEPLOY_TIME"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "create-react-app"
  command = "npm start"
  targetPort = 3000
  port = 8888
  publish = "build"
  autoLaunch = true

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[template.environment]
  REACT_APP_NETLIFY_SITE_URL = "https://cultural-shrine-village.netlify.app"
  REACT_APP_API_URL = "/.netlify/functions"