[package]
name = "shrine_contracts"
version = "2.0.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.0"

[[target.starknet-contract]]
sierra = true

[scripts]
build = "scarb build"
test = "scarb cairo-test"
format = "scarb fmt"